---
title: ""
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'cti.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---

## Center for Teaching Innovation Graduate Teaching Fellowship

[Cornell University's Center for Teaching Innovation (CTI) Graduate Teaching Fellows program](https://teaching.cornell.edu/cti-graduate-teaching-fellowship) brings together experienced, creative graduate students with teaching experience at Cornell and an interest in teaching and learning. To join the program, prospective CTI Fellows must submit an application and participate in an interview process. Teaching fellows work closely with CTI staff to design and implement teaching workshops, events, and resources to foster teaching excellence, innovation, and networking across the university. The program offers participants an opportunity to reflect on their teaching and communication skills as they develop leadership, mentorship, and interdisciplinary collaborative skills.

I participated in the CTI Fellows program for three of my four years at Cornell, taking on a greater leadership role in each year. I detail my role, responsibility, and experience for each year in the program in the other tabs in this section. 