---
title: ""
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'philosophy.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---


## Teaching Philosophy
As a statistics instructor, my goal is to prepare students to apply quantitative skills to real-world problems. Teaching is not just about showcasing a new topic in the classroom. Instead, it is about giving students the skills they need to continue learning and using statistics in their future classes and careers. I accomplish this goal of **instilling lifelong learning** through an emphasis on **real-world examples, consistent in-class practice, and transferable skills**.

\noindent
The field of statistics does not exist in a vacuum, and nor should a class on statistics. In order for students to be able to use the skills they gain in my classes in their future careers, they need to practice selecting and deploying appropriate techniques and methods on **real-world problems**. As a TA in computing labs for graduate and undergraduate students, I accomplished this goal by helping students develop exploratory data analysis and assumption checking practices, using examples from public health disciplines. For instance, after I introduce students to methods for paired samples (i.e. Permutation tests, Wilcoxon Signed Rank tests), I ask them to select the appropriate statistical test for a study of new clinical guidelines on radiation dosages for lung cancer patients. We begin the example with exploratory data analysis exercises, where students examine distributions and summary statistics of clinic-average radiation doses from before and after the introduction of new practice guidelines. They answer questions that help them check the assumptions of the tests, like: *Is the shape of the distribution of dosages constant across time? What is the mean dosage before and after the change? What about the median?* With intuition from the plots, students conclude that a Wilcoxon Signed Rank test is *not* meaningful for their analysis, as the median radiation dosage remains constant across the guideline change, but the variance of the dosages narrows substantially. In the future, if they struggle to identify the appropriate statistical method for a problem at hand, they can repeat this exercise to explore their data and verify the assumptions of a given analysis. 

My practice of including real-world projects, examples, and datasets in course material is complemented by my emphasis on **consistent in-class practice and feedback**. In larger classes, I will incorporate real-time practice and feedback with low-stakes iClicker and PollEverywhere questions. For every new concept or learning outcome, these formative assessments not only help students identify areas they need to study, they also inform my lesson planning. I will be able to adapt the amount of time I spend on concepts based on the results of in-class quizzing. In smaller courses, I plan to implement in-class practice in different ways. For example, in a course I have designed, entitled *Statistical Graphics and Communication*, one of my learning goals is for students to be able to verbally describe and critique a statistical graphic from the media. When I teach this class, I will scaffold this skill by providing students a graph from the media each week, along with a standard set of guidelines for interpreting the plot. During a lab or active learning session, I will pull aside a sample of students, one at a time, to practice verbally presenting the graph to me. This practice is deliberately low-stakes – students receive credit for participating, and I provide feedback that helps them excel on later presentations and summative assessments. 

In the same way that frequent practice and feedback makes expectations clear for students, my course organization makes the **transferability of statistical concepts** clear for students' future careers. For example, I will not only state what the learning goals are for my class, I will also explain *why* those goals are important for professionals in a variety of fields. Specifically, I will discuss how students can use course materials to continue learning in an advanced course or show their knowledge to a future employer. This practice helps students understand how their learning experience can help them achieve their unique professional goals. In my *Statistical Graphics and Communication* syllabus, I connect the core components of the course, like lecture notes, lab exams, and final projects, to the skills that students should have by the end of the semester. Moreover, I emphasize tangible products that students can take from the class and use in application materials, including formal statistical reports, a research poster, and a web application. I find that this transparency helps students understand the importance of course topics and assignments, while providing clear evidence of the transferability of classroom skills in future careers.

In my classes, students are welcomed to data science concepts with real-world examples, in-class problem-solving, and a clear appreciation for the importance of what they are about to learn. These aspects of my teaching promote lifelong learning in my students as they pursue their own career goals and aspirations.

### Commitment to Teaching Excellence
To refine my own teaching approach and practices, I have engaged in thorough pedagogical training at multiple institutions. While a student at the University of Michigan, I took a course on *Effective Teaching in Public Health*, which prepared me for my TA roles in introductory biostatistics classes for graduate and undergraduate students. At Cornell University, I have served as a Graduate Senior Lead Teaching Fellow with the Center for Teaching Innovation (CTI) since 2021. In this program, I reflected on my teaching practice through biannual teaching training, biweekly teaching discussions, and periodic teaching exercises. These experiences give me a toolkit to evaluate my own teaching success, and to continue developing and refining my teaching practice throughout my career. 

I am also passionate about sharing teaching strategies and techniques with my broader community. Through my work with the CTI, I currently develop and facilitate multiple teaching workshops and conferences, with a focus on graduate and post-doctoral level trainees. In addition, through a competitive *Belonging at Cornell* grant, a colleague and I developed an in-depth program for early-career graduate TAs at Cornell, entitled the *Advanced Graduate Teaching Cohort*. As part of the intensive, multiday program, I developed materials and exercises on evidence-based inclusive teaching strategies, creating high-structure classrooms, and further developing teaching strategies for the cohort members. Given my prior experiences in the area of teaching training, I welcome opportunities to mentor early-career colleagues in their teaching development.

### Teaching Experience and Preparedness
At Cornell University, I served as a TA for multiple graduate and undergraduate courses and led various TA development programs. I have worked with class sizes between 15 and 125 students, and my teaching modality has been both in-person and online (with both synchronous and asynchronous components).

I am prepared to teach introductory statistics and data science courses for undergraduate, graduate, and professional students. In addition, due to the nature of my research, I would also gladly teach graduate courses on categorical data analysis, measurement error methods, and statistical consulting and communication. My commitment to teaching excellence and my past pedagogical training also prepares me to teach pedagogy skills at the graduate and post-doctoral level, including TA trainings. In addition, I look forward to teaching students through research experiences. 